Rewrite to move to AWS Lambda
thaliawww/what-are-we-eating-today pull request #59
Opened 2020-03-09 17:47 UTC by pingiun

Closes #56 #45

### Summary
- Replaced pugsql with AWS DynamoDB invocations.
- Rewrote certain parts for AWS lambda things
- Added GitHub action to deploy on Lambda

### How to test
We'll wait to see if it works on Wednesday?

2020-03-09 17:52 UTC, joren485 commented on .github/workflows/test.yaml
>          - name: Setup Poetry
This still says "Poetry"

2020-03-12 08:00 UTC, joren485 requested changes
The README still contains info about `poetry`.

2020-03-12 08:00 UTC, joren485 commented on .github/workflows/deploy.yaml
> +          run: |
This does not have to be a multiline item.

2020-03-12 08:00 UTC, joren485 commented on .github/workflows/deploy.yaml
> +        - name: Deploy slash command
Please add some documentation on how to use this.

2020-11-23 19:21 UTC, se-bastiaan approved these changes

2020-11-23 19:21 UTC, merged